class Mug{
public static void main(String[]args){
String surName="Hiremath";
System.out.println("surName:"+surName);
String doorNo="6218";
System.out.println("doorNo:"+doorNo);
String data=surName+doorNo;
System.out.println("data:"+data);
String area="Jayanagar 5th Block";
System.out.println("area:"+area);
String pincode="586128";
System.out.println("pincode:"+pincode);
String additions=area+pincode;
System.out.println(" additions:"+ additions);
String address="Vijayapur road Sindagi";
System.out.println("address:"+address);
String rollNo="2BL20EC";
System.out.println("rollNo:"+rollNo);
String check=address+rollNo;
System.out.println("check:"+check);
String greetings="Hello Good Morning";
System.out.println("greetings:"+greetings);
String ticketNo="123GHI67";
System.out.println("ticketNo:"+ticketNo);
String count=greetings+ticketNo;
System.out.println("count:"+count);
String message="There is no holiday tommorow";
System.out.println("message:"+message);
String university="VTU Belagavi";
System.out.println("university:"+university);
String search=message+university;
System.out.println("search:"+search);
String school="Padmaraj Public school";
System.out.println("school:"+school);
String password="Hiremath@123";
System.out.println("password:"+password);
String document=school+password;
System.out.println("document:"+document);
String email="bhagya@gmail.com";
System.out.println("email:"+email);
String userName="bhavana@43";
System.out.println(" userName:"+ userName);
String addendums=email+userName;
System.out.println("addendums:"+ addendums);
String students="students are attending classes reguraly";
System.out.println("students:"+students);
String campus="BLDEA campus surrounded by different building blocks";
System.out.println("campus:"+campus);
String details=students+campus;
System.out.println("details:"+details);
String activities="various activities performed in school";
System.out.println("activities:"+activities);
String placements="Different college are conducting placements";
System.out.println(" placements:"+placements);
String information=activities+placements;
System.out.println("information:"+information);
String nickName="cherry";
System.out.println("nickName:"+nickName);
String location="beside Ram mandir Gulbarga";
System.out.println("location:"+location);
String input=nickName+location;
System.out.println("input:"+input);
String residence="beside whitefield Bangalore";
System.out.println("residence:"+residence);
String appellation="chutki";
System.out.println("appellation:"+appellation);
String specifies=residence+appellation;
System.out.println("specifies:"+specifies);
String projectTitle="Electronic train ticket machine";
System.out.println("projectTitle:"+projectTitle);
String title="sizuka";
System.out.println("title:"+title);
String Buffer=projectTitle+title;
System.out.println("Buffer:"+Buffer);
String pseudonym="venu";
System.out.println("pseudonym:"+pseudonym);
String designation="chetanaa";
System.out.println("designation:"+designation);
String features=pseudonym+designation;
System.out.println("features:"+features);
String specialization="Electronics and Communication";
System.out.println("specialization:"+specialization);
String stream="E&C";
System.out.println("stream:"+stream);
String proof=specialization+stream;
System.out.println("proof:"+proof);
String batch="2024";
System.out.println("batch:"+batch);
String hobbies="it includes dancing ,travelling";
System.out.println("hobbies:"+hobbies);
String figures=batch+hobbies;
System.out.println("figures:"+figures);
String depart="train is departed at station";
System.out.println("depart:"+depart);
String deviate="dividing at two equal direction";
System.out.println("deviate:"+deviate);
String particulars=depart+deviate;
System.out.println("particulars:"+particulars);
String enroute="enrouting to hyderabad";
System.out.println("enroute:"+enroute);
String administration="college administrator is responsible for activities in college";
System.out.println("administration:"+administration);
String intelligence=enroute+administration;
System.out.println("administration:"+administration);
String supervision="In exams lecturers supervision students";
System.out.println("supervision:"+supervision);
String management="any faults that happens in college it is responsible by college management";
System.out.println("management:"+management);
String gen=supervision+management;
System.out.println("gen:"+gen);
String relish="enjoy the moment";
System.out.println("relish:"+relish);
String joy="living the every moment";
System.out.println("joy:"+joy);
String ammunition=relish+joy;
System.out.println("ammunition:"+ammunition);
String festival="celebrating every festival without missing ";
System.out.println("festival:"+festival);
String street="every street are busy on weekends";
System.out.println("street:"+street);
String dossier=festival+street;
System.out.println("dossier:"+dossier);
String blissful="making a parents proud is happiest moment";
System.out.println("blissful:"+blissful);
String celebrity="they were a different types of dresses in their film ";
System.out.println("celebrity:"+celebrity);
String lowdown=blissful+celebrity;
System.out.println("lowdown:"+lowdown);
String star="stars are twinkling in the sky";
System.out.println("star:"+star);
String superStar="being a superstar isn't easy";
System.out.println("superStar:"+superStar);
String teligence=star+superStar;
System.out.println("teligence:"+teligence);
String television=" a form of mass media based on the electronic delivery of moving images and sound from a source to a receiver.";
System.out.println(" television:"+ television);
String telegram="is a cloud-based, cross-platform, instant messaging service.";
System.out.println("telegram:"+telegram);
String info=television+telegram;
System.out.println("info:"+info);
String communication="the act of sharing or exchanging information, ideas or feelings";
System.out.println("communication:"+communication);
String massCommunication="the process by which a person, group of people or organization creates a message and transmits it through some type of medium to a large, anonymous, heterogeneous audience";
System.out.println("massCommunication:"+massCommunication);
String stastics=communication+massCommunication;
System.out.println("stastics:"+stastics);
String broadcasting="electronic transmission of radio and television signals that are intended for general public reception";
System.out.println("broadcasting:"+broadcasting);
String media="the means of communication, as radio and television, newspapers, magazines, and the internet, that reach or influence people widely";
System.out.println("media:"+media);
String feedin=broadcasting+media;
System.out.println("feedin:"+feedin);
String newspaper="a paper that is printed and distributed usually daily or weekly and that contains news, articles of opinion, features, and advertising";
System.out.println("newspaper:"+newspaper);
String advertisement="the means of communication in which a product, brand or service is promoted to a viewership in order to attract interest, engagement, and sales.";
System.out.println("advertisement:"+advertisement);
String load=newspaper+advertisement;
System.out.println("load:"+load);
String article="a piece of writing in a newspaper or magazine";
System.out.println("article:"+article);
String magazine="a type of large thin book with a paper cover that you can buy every week or month containing articles, photographs, etc. often on a particular topic";
System.out.println("magazine:"+magazine);
String putin=article+magazine;
System.out.println("putin:"+putin);
String topic="a subject that you talk, write or learn about";
System.out.println("topic:"+topic);
String section="one of the parts into which something is divided";
System.out.println("section:"+section);
String insert=topic+section;
System.out.println("insert:"+insert);
String sentence="a group of words that makes complete sense. It begins with a capital letter and ends with a full stop.";
System.out.println("sentence:"+sentence);
String statement=" a sentence that says something is true.";
System.out.println("statement:"+statement);
String code=sentence+statement;
System.out.println("code:"+code);
String logic=" the study of correct reasoning.";
System.out.println("logic:"+logic);
String formation=" the giving or receiving of knowledge or intelligence";
System.out.println("formation:"+formation);
String capture=logic+formation;
System.out.println("capture:"+capture);
String knowledge="the state of knowing about a particular fact or situation";
System.out.println("knowledge:"+knowledge);
String patience="the ability to wait, or to continue doing something despite difficulties, or to suffer without complaining or becoming annoyed";
System.out.println("patience:"+patience);
String store=knowledge+patience;
System.out.println("store:"+store);
String complain="to say that you are not satisfied with or happy about something";
System.out.println("complain:"+complain);
String satisfy="to fulfill the desires, expectations, needs, or demands of (a person, the mind, etc.); give full contentment to";
System.out.println("satisfy:"+satisfy);
String process=complain+satisfy;
System.out.println("process:"+process);
String verify="to check or state that something is true";
System.out.println(" verify:"+ verify);
String laboratory="a room or building that is used for scientific research, testing, experiments, etc. or for teaching about science";
System.out.println(" laboratory:"+ laboratory);
String keyin=verify+laboratory;
System.out.println("keyin:"+keyin);
String measurement="a technique in which the properties of an object are determined by comparing them to a standard quantity.";
System.out.println("measurement:"+measurement);
String compare="to say that somebody/something is similar to somebody/something else";
System.out.println("compare:"+compare);
String add=measurement+compare;
System.out.println("add:"+add);
String significance="having the quality of being important.";
System.out.println(" significance:"+ significance);
String evident=" It quickly became evident that someone had broken in.";
System.out.println(" evident:"+ evident);
String introduce=significance+evident;
System.out.println("introduce:"+introduce);
String obvious="easily seen or understood";
System.out.println("obvious:"+obvious);
String telepathy="the communication of thoughts between people’s minds without using speech, writing or other normal methods";
System.out.println("telepathy:"+telepathy);
String log=obvious+telepathy;
System.out.println("log:"+log);
String intakes = "the amount of food, drink, etc. that you take into your body";
System.out.println("intakes:"+intakes);
String assumption="something that you accept is true even though you have no proof";
System.out.println("assumption:"+assumption);
String increments=intakes+assumption;
System.out.println("increments:"+increments);
String quality = "how good or bad something is";
System.out.println("quality:"+quality);
String quantify="to measure or judge the size or amount of something";
System.out.println("quantify:"+quantify);
String qualitative=quality+quantify;
System.out.println("qualitative:"+qualitative);
String inherit = "to receive property, money, etc. from somebody who has died";
System.out.println("inherit:"+inherit);
String fur="he soft thick hair that covers the bodies of some animals";
System.out.println("fur:"+fur);
String incentive=inherit+fur;
System.out.println("incentive:"+incentive);
String coat = "a piece of clothing that you wear over your other clothes to keep warm when you are outside";
System.out.println("coat:"+coat);
String heraldry="the study of the history of old and important families and their special family symbols";
System.out.println("assumption:"+assumption);
String innovative=coat+heraldry;
System.out.println("innovative:"+innovative);
String offense = "a transgression of the law; misdemeanor";
System.out.println("inherit:"+inherit);
String intend="to plan or mean to do something";
System.out.println("fur:"+fur);
String hardwork=inherit+fur;
System.out.println("hardwork:"+hardwork);
String steal = "to take something from a person, shop, etc. without permission and without intending to return it or pay for it";
System.out.println("steal :"+steal );
String pursue="to follow someone or something, usually to try to catch him, her, or it";
System.out.println("pursue:"+pursue);
String informative=steal+pursue;
System.out.println("informative:"+informative);
String undecide = "not having made a decision";
System.out.println("undecide:"+undecide);
String uncertain="to be unsure of something";
System.out.println("uncertain:"+uncertain);
String into=undecide+uncertain;
System.out.println("into:"+into);
String doubt = "to be uncertain about something or someone, or to have difficulty believing something";
System.out.println("doubt:"+doubt);
String assure="to promise or tell something to someone confidently or firmly, or to cause someone to feel certain by removing doubt";
System.out.println("assure:"+assure);
String center=doubt+assure;
System.out.println("incentive:"+incentive);
String assertive = "behaves confidently and is not frightened to say what they want or believe";
System.out.println("assertive:"+assertive);
String affect="to make somebody feel very sad, angry, etc";
System.out.println("affect:"+affect);
String insensitive=assertive+affect;
System.out.println("insensitive:"+insensitive);
String transagression = "breach crime error fault infraction infringement lapse misdeed misdemeanor sin wrongdoing.";
System.out.println("transagression:"+transagression);
String infraction="an infraction of the rules";
System.out.println("infraction:"+infraction);
String inflammable=transagression+infraction;
System.out.println("inflammable:"+inflammable);
String violation = "a breach, infringement, or transgression, as of a law, rule, promise, etc";
System.out.println("violation:"+violation);
String infringement="an act of infringing.";
System.out.println("infringement:"+infringement);
String incorrective=violation +infringement;
System.out.println("incorrective:"+incorrective);
String obligation = "the state of having to do something because it is a law or duty, or because you have promised";
System.out.println("obligation:"+obligation);
String contract="a written legal agreement";
System.out.println("contract:"+contract);
String impassive=obligation+contract;
System.out.println("impassive:"+impassive);
String illness = "an unhealthy condition of body or mind";
System.out.println("illness:"+illness);
String impact="an effect or impression";
System.out.println(" impact:"+ impact);
String incorrect=illness+ impact;
System.out.println("incorrect:"+incorrect);
String crash = "to have an accident in a vehicle; to drive a vehicle into something";
System.out.println("crash:"+crash);
String cramp="a sudden pain that you get in a muscle, that makes it difficult to move";
System.out.println("cramp:"+cramp);
String intentive=crash+cramp;
System.out.println("intentive:"+intentive);
String introvert = "a person whose personality is characterized by introversion";
System.out.println("introvert:"+introvert);
String inmessionante=" a player who has flawless ability on the ball.";
System.out.println("inmessionante:"+inmessionante);
String flawless=introvert+inmessionante;
System.out.println("flawless:"+flawless);












}
}